### ISSUE TITLE
Don't catch and hide exceptions when loading modules

### ISSUE THREAD

**Issue by ssfrr** [DanChianucci/Eagle2Kicad#29]
The first time I tried to run Start.py the only output I got was:
```
Traceback (most recent call last):
  File "Start.py", line 245, in <module>
    main()
  File "Start.py", line 237, in main
    startGui()
  File "Start.py", line 27, in startGui
    root = Tk()
NameError: name 'Tk' is not defined
```

After removing the try-catch block around `import_tk` I got the much more helpful error message:
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/tkinter/__init__.py", line 39, in <module>
    import _tkinter
ImportError: No module named '_tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Start.py", line 242, in <module>
    main()
  File "Start.py", line 234, in main
    startGui()
  File "Start.py", line 22, in startGui
    import_tk()
  File "Start.py", line 15, in import_tk
    from tkinter import Tk, Frame, Label, Button, RIDGE, BOTH, X
  File "/usr/lib/python3.4/tkinter/__init__.py", line 41, in <module>
    raise ImportError(str(msg) + ', please install the python3-tk package')
ImportError: No module named '_tkinter', please install the python3-tk package
```

It seems like swallowing the errors that are thrown makes it much more difficult to figure out what's going on.

**Comment by DanChianucci** [comment]
Commit e7b6e949e822a050b02c32ffed976b256e68254f fixes this
