### ISSUE TITLE
XML parsing error

### ISSUE THREAD

**Issue by bmeneguele** [DanChianucci/Eagle2Kicad#30]
Hello, trying to convert this LBR http://www.embeddedartists.com/sites/default/files/support/xpr/LPCXpresso_Boards_EAGLE_lib.zip I receive back an error about XML parser error:

*******************************************
Converting Lib: lpcxpresso.lbr
Module Output: lpcxpresso.mod
Symbol Output: lpcxpresso.lib
Lib Name: lpcxpresso

Error Converting Library: 'lpcxpresso'
Traceback (most recent call last):
  File "/home/bmeneg/Downloads/Eagle2Kicad-master/Start.py", line 153, in convertLib
    node = getRootNode(fileName)
  File "/home/bmeneg/Downloads/Eagle2Kicad-master/Start.py", line 69, in getRootNode
    node.parse(fileName, parser)
  File "/usr/lib/python3.4/xml/etree/ElementTree.py", line 604, in parse
    parser.feed(data)
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0

*******************************************

Would you know what kind of issue is that? I mean, do you know the solution? :)
Thanks.

**Comment by abetusk** [comment]
I think Eagle2Kicad only supports XML-as-text?  Can you try opening that library up in Eagle, saving as XML and trying again to convert?  A quick Googling found [this](http://www.element14.com/community/thread/27185/l/xml-format-for-libraries?displayFullThread=true) link on a message board from element14.
