### ISSUE TITLE
readme outdated or wrong

### ISSUE THREAD

**Issue by nonchip** [DanChianucci/Eagle2Kicad#38]
there's no `Eagle2Kicad` executable/script/whatever in the repo, but documented in the readme.

the `Start.py` script complains about requiring TKinter for a GUI that's not documented at all.

also IMHO such a GUI should be optional, as I (and possibly many other users) would be possibly fine with using just the CLI as documented.

**Comment by abetusk** [comment]
@nonchip nonchip, I had to install some `Tk` libraries to get it working.  I'm not sure if this will do it but you might want to try the following:

```
sudo apt-get install python-tksnack python-tk pypy-tk
```

Some of those packages might be superfluous.

Eagle2Kicad also requires Python3.  After install the above packages, this "worked for me":

```
python3 Start.py
```

In response to your request for a dependency free command line version, [I made a fork of this project](https://github.com/abetusk/Eagle2Kicad) and made a "proper" executable that does not require Tk called [eagle2kicad](https://github.com/abetusk/Eagle2Kicad/blob/release/eagle2kicad).  Feel free to take a look.

**Comment by nonchip** [comment]
@abetusk i'm on void linux, so the command is different, but i also just needed the cli anyway. but then it turned out i have no clue what to do with the produced files, as kicad seems to want some folder structure they call `.pretty` and don't really document...

i see your version also uses the `"inFile", "symFile", "modFile"` scheme, could you tell me what to do with those to get them into kicad?

**Comment by abetusk** [comment]
@nonchip, I think this is getting into more KiCAD specific territory.  I haven't used KiCAD in a while but I think there have been updates, including maybe using new module files (what was previously `.mod` is now `.pretty`?).

The `inFile` is the input Eagle file, just as it is with this version of the repository.  I believe the `symFile` is the output KiCAD schematic library file and the `modFile` is the output footprint library file.  You'll need to figure out out to convert those over to what KiCAD expects and figure out how to import them.  This might be as easy as pointing KiCAD to those newly derived files and/or renaming them with the extensions it expects (such as `.pretty`).  You'll have to consult KiCAD documentation or other online resources.

**Comment by ghost** [comment]
I added "#!/usr/bin/env python3" to the top of Start.py and chmod 755 Start.py, and had to "sudo apt-get install python3-tk" to get it to run at all. And after all that it still didn't work. My .brd file IS from Eagle, but it's in some binary format not xml, so maybe it's from some other version than 6.x. The script should be able to detect and say that instead of just:
<pre>
 bkw@negre:~/src/Eagle2Kicad$ ./Start.py
 Conversion Failed
 Traceback (most recent call last):
  File "./Start.py", line 101, in convertBoard
    node = getRootNode(fileName)
  File "./Start.py", line 71, in getRootNode
    node.parse(fileName, parser)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 603, in parse
    parser.feed(data)
  File "<string>", line None
 xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
</pre>

The file I'm trying to convert is Rex.brd from inside of REX_STD.zip from here http://www.club100.org/memfiles/index.php?&direction=0&order=&directory=Steve%20Adolph/REX/info

OSH Park accepts the brd file, so it's at least a valid file of some sort.

**Comment by gh-jmg** [comment]
Did you try loading this Eagle file directly into the latest (nightly) KiCad to check ?
http://downloads.kicad-pcb.org/windows/nightly/
V5 has a better native Eagle file loader.

If that does not load, you could ask the authors of your link, to include a Eagle format version that does load ?
